### ISSUE TITLE
Please bump golang.org/x/crypto dependency

### ISSUE THREAD

**Issue by afunix** [SSLMate/go-pkcs12#44]
`go.mod` has `golang.org/x/crypto@v0.0.0-20220331220935-ae2d96664a29`, which in order depends on `golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2` which has a number of known vulnerabilities (CVE-2022-41723, CVE-2022-44716, CVE-20220-41717).
Can you please bump `golang.org/x/crypto` to `v0.4.0`?

**Comment by 7ing** [comment]
Also, this project is still using `go 1.15`, hopefully could bump the version up in next release.

**Comment by AGWA** [comment]
I increased the versions in `go.mod` yesterday, but for the record, none of the vulnerabilities in `golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2` could be reached by code in go-pkcs12.  You have to use a tool like [govulncheck](https://go.dev/blog/govulncheck) to determine whether you are vulnerable or not; vulnerability scanners that just look at version numbers produce a huge amount of noise and should no longer be used now that govulncheck has reached version 1.0.0.  Moving forward, I am not going to release a new version of go-pkcs12 any time a dependency or transitive dependency has an unreachable vulnerability, as doing so creates unnecessary work for myself and projects which depend on go-pkcs12.

Also note that you can specify a higher version of a module in the main module's go.mod file, and Go will select that instead of the version in go-pkcs12's go.mod file, in case you do need to use a higher version of a dependency for some reason.
